---
version: '3'
services:
    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        container_name: ${APP_NAME:?err}-app
        volumes:
            - data: ./boxfuse-sample-java-war-hello/target
    tomcat:
        build:
            context: ./tomcat
            dockerfile: Dockerfile
        container_name: ${APP_NAME:?err}-tomcat
        ports:
            - 8080:8080
        volumes:
            - data: /usr/local/tomcat/webapps/
        depends_on:
            - app
volumes:
    data:
    external: true