---
version: '3.2'
services:
    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        container_name: app
        volumes:
            - data:./app/boxfuse-sample-java-war-hello/target/
    tomcat:
        build:
            context: ./tomcat
            dockerfile: Dockerfile
        container_name: tomcat
        ports:
            - 8080:8080
        volumes:
            - data:/usr/local/tomcat/webapps/
        depends_on:
            - app
volumes:
    data:
    